// File generated by FlutterFire CLI, normally.
//
// This is a HAND-WRITTEN PLACEHOLDER. Before running the app, replace this
// file by running from the flutter_app/ directory:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure --project=tagusheep-72229
//
// That command registers Android/iOS apps against the existing Tagsheep
// Firebase project and regenerates this file with real values. It reuses
// the same project the Next.js web app already talks to (see
// ../.firebaserc), so mobile-created tags show up on the website and vice
// versa — no separate backend needed.
//
// The `web` block below is filled from ../.env.example's key names so the
// shape is obvious; the actual values live in your Firebase Console
// (Project settings -> General -> Your apps) and are NOT committed here
// since they're per-project secrets-adjacent config.
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform. '
          'Run `flutterfire configure` from flutter_app/.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    appId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    messagingSenderId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    projectId: 'tagusheep-72229',
    authDomain: 'tagusheep-72229.firebaseapp.com',
    storageBucket: 'tagusheep-72229.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    appId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    messagingSenderId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    projectId: 'tagusheep-72229',
    storageBucket: 'tagusheep-72229.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    appId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    messagingSenderId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    projectId: 'tagusheep-72229',
    storageBucket: 'tagusheep-72229.firebasestorage.app',
    iosBundleId: 'com.tagusheep.tagusheepMobile',
  );
}
